// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL1ctGyXO42YcYiEHwCBcZ7zbqSXmmTOQ',
    appId: '1:662006036899:web:e0cd2a196dcd6524338216',
    messagingSenderId: '662006036899',
    projectId: 'ikara-app',
    authDomain: 'ikara-app.firebaseapp.com',
    databaseURL: 'https://ikara-app-default-rtdb.firebaseio.com',
    storageBucket: 'ikara-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4EK6oB_TkgY2RIo_oX5yA892qQxMUgu0',
    appId: '1:662006036899:android:2574d8430a2035b4338216',
    messagingSenderId: '662006036899',
    projectId: 'ikara-app',
    databaseURL: 'https://ikara-app-default-rtdb.firebaseio.com',
    storageBucket: 'ikara-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwf5VDKlQAQEl8HyjJrkzBLY2fdx5jJLY',
    appId: '1:662006036899:ios:010345c32a5cde89338216',
    messagingSenderId: '662006036899',
    projectId: 'ikara-app',
    databaseURL: 'https://ikara-app-default-rtdb.firebaseio.com',
    storageBucket: 'ikara-app.firebasestorage.app',
    iosClientId: '662006036899-135jvt7jvcd6f8s5aa8vph6m0tk5kikc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ikaraClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwf5VDKlQAQEl8HyjJrkzBLY2fdx5jJLY',
    appId: '1:662006036899:ios:010345c32a5cde89338216',
    messagingSenderId: '662006036899',
    projectId: 'ikara-app',
    databaseURL: 'https://ikara-app-default-rtdb.firebaseio.com',
    storageBucket: 'ikara-app.firebasestorage.app',
    iosClientId: '662006036899-135jvt7jvcd6f8s5aa8vph6m0tk5kikc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ikaraClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL1ctGyXO42YcYiEHwCBcZ7zbqSXmmTOQ',
    appId: '1:662006036899:web:cdf7a42734475594338216',
    messagingSenderId: '662006036899',
    projectId: 'ikara-app',
    authDomain: 'ikara-app.firebaseapp.com',
    databaseURL: 'https://ikara-app-default-rtdb.firebaseio.com',
    storageBucket: 'ikara-app.firebasestorage.app',
  );

}